from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List


@dataclass(frozen=True)
class CatalogItem:
    id: str
    name: str
    template_labels: List[str]  

def default_catalog() -> Dict[str, CatalogItem]:
    """
    Replace these with real items over time.
    template_labels correspond to template filenames, e.g. assets/templates/G.webp => label "G"
    """
    items = [
        CatalogItem(id="advanced_arc_powercell", name="Advanced ARC Powercell", template_labels=["advanced_arc_powercell"]),
        CatalogItem(id="advanced_electrical_components", name="Advanced Electrical Components", template_labels=["advanced_electrical_components"]),
        # CatalogItem(id="advanced_mechanical_components", name="Advanced Mechanical Components", template_labels=["advanced_mechanical_components"]),
        # CatalogItem(id="agave", name="Agave", template_labels=["agave"]), 
        # CatalogItem(id="agave_juice", name="Agave Juice", template_labels=["agave_juice"]), 
        # CatalogItem(id="air_freshener", name="Air Freshener", template_labels=["air_freshener"]), 
        # CatalogItem(id="alarm_clock", name="Alarm Clock", template_labels=["alarm_clock"]), 
        CatalogItem(id="antiseptic", name="Antiseptic", template_labels=["antiseptic"]),
        CatalogItem(id="apricot", name="Apricot", template_labels=["apricot"]),
        CatalogItem(id="arc_alloy", name="ARC Alloy", template_labels=["arc_alloy"]),
        CatalogItem(id="arc_circuitry", name="ARC Circuitry", template_labels=["arc_circuitry"]),
        # CatalogItem(id="arc_coolant", name="ARC Coolant", template_labels=["arc_coolant"]), 
        CatalogItem(id="arc_flex_rubber", name="ARC Flex Rubber", template_labels=["arc_flex_rubber"]),
        CatalogItem(id="arc_motion_core", name="ARC Motion Core", template_labels=["arc_motion_core"]),
        CatalogItem(id="arc_performance_steel", name="ARC Performance Steel", template_labels=["arc_performance_steel"]),
        # CatalogItem(id="arc_powercell", name="ARC Powercell", template_labels=["arc_powercell"]),
        CatalogItem(id="arc_synthetic_resin", name="ARC Synthetic Resin", template_labels=["arc_synthetic_resin"]),
        # CatalogItem(id="arc_thermo_lining", name="ARC Thermo Lining", template_labels=["arc_thermo_lining"]),
        CatalogItem(id="assorted_seeds", name="Assorted Seeds", template_labels=["assorted_seeds"]),
        # CatalogItem(id="bastion_cell", name="Bastion Cell", template_labels=["bastion_cell"]),
        CatalogItem(id="battery", name="Battery", template_labels=["battery"]),
        CatalogItem(id="bicycle_pump", name="Bicycle Pump", template_labels=["bicycle_pump"]),
        # CatalogItem(id="bloated_tuna_can", name="Bloated Tuna Can", template_labels=["bloated_tuna_can"]),
        # CatalogItem(id="bombardier_cell", name="Bombardier Cell", template_labels=["bombardier_cell"]),
        # CatalogItem(id="breathtaking_snow_globe", name="Breathtaking Snow Globe", template_labels=["breathtaking_snow_globe"]),
        CatalogItem(id="broken_flashlight", name="Broken Flashlight", template_labels=["broken_flashlight"]),
        # CatalogItem(id="broken_guidance_system", name="Broken Guidance System", template_labels=["broken_guidance_system"]),
        # CatalogItem(id="broken_handheld_radio", name="Broken Handheld Radio", template_labels=["broken_handheld_radio"]),
        CatalogItem(id="broken_taser", name="Broken Taser", template_labels=["broken_taser"]),
        # CatalogItem(id="burned_arc_circuity", name="Burned ARC Circuity", template_labels=["burned_arc_circuity"]),
        CatalogItem(id="camera_lens", name="Camera Lens", template_labels=["camera_lens"]),
        # CatalogItem(id="candleberries", name="Candleberries", template_labels=["candleberries"]),
        # CatalogItem(id="candle_holder", name="Candle Holder", template_labels=["candle_holder"]),
        CatalogItem(id="canister", name="Canister", template_labels=["canister"]),
        CatalogItem(id="cat_bed", name="Cat Bed", template_labels=["cat_bed"]),
        CatalogItem(id="chemicals", name="Chemicals", template_labels=["chemicals"]),
        CatalogItem(id="coffee_pot", name="Coffee Pot", template_labels=["coffee_pot"]),
        CatalogItem(id="complex_gun_parts", name="Complex Gun Parts", template_labels=["complex_gun_parts"]),
        CatalogItem(id="coolant", name="Coolant", template_labels=["coolant"]),
        # CatalogItem(id="cooling_coil", name="Cooling Coil", template_labels=["cooling_coil"]),
        # CatalogItem(id="cooling_fan", name="Cooling Fan", template_labels=["cooling_fan"]),
        CatalogItem(id="cracked_bioscanner", name="Cracked Bioscanner", template_labels=["cracked_bioscanner"]),
        CatalogItem(id="crude_explosives", name="Crude Explosives", template_labels=["crude_explosives"]),
        # CatalogItem(id="crumpled_plastic_bottle", name="Crumpled Plastic Bottle", template_labels=["crumpled_plastic_bottle"]),
        # CatalogItem(id="damaged_arc_motion_core", name="Damaged ARC Motion Core", template_labels=["damaged_arc_motion_core"]),
        # CatalogItem(id="damaged_arc_powercell", name="Damaged ARC Powercell", template_labels=["damaged_arc_powercell"]),
        # CatalogItem(id="damaged_fireball_burner", name="Damaged Fireball Burner", template_labels=["damaged_fireball_burner"]),
        CatalogItem(id="damaged_heat_sink", name="Damaged Heat Sink", template_labels=["damaged_heat_sink"]),
        # CatalogItem(id="damaged_hornet_driver", name="Damaged Hornet Driver", template_labels=["damaged_hornet_driver"]),
        # CatalogItem(id="damaged_rocketeer_driver", name="Damaged Rocketeer Driver", template_labels=["damaged_rocketeer_driver"]),
        # CatalogItem(id="damaged_tick_pod", name="Damaged Tick Pod", template_labels=["damaged_tick_pod"]),
        # CatalogItem(id="damaged_wasp_driver", name="Damaged Wasp Driver", template_labels=["damaged_wasp_driver"]),
        # CatalogItem(id="dart_board", name="Dart Board", template_labels=["dart_board"]),
        # CatalogItem(id="deflated_football", name="Deflated Football", template_labels=["deflated_football"]),
        # CatalogItem(id="degraded_arc_rubber", name="Degraded ARC Rubber", template_labels=["degraded_arc_rubber"]),
        CatalogItem(id="diving_goggles", name="Diving Goggles", template_labels=["diving_goggles"]),
        CatalogItem(id="dog_collar", name="Dog Collar", template_labels=["dog_collar"]),
        # CatalogItem(id="dried_out_arc_resin", name="Dried Out ARC Resin", template_labels=["dried_out_arc_resin"]),
        CatalogItem(id="duct_tape", name="Duct Tape", template_labels=["duct_tape"]),
        # CatalogItem(id="durable_cloth", name="Durable Cloth", template_labels=["durable_cloth"]),
        # CatalogItem(id="electrical_components", name="Electrical Components", template_labels=["electrical_components"]),
        CatalogItem(id="empty_wine_bottle", name="Empty Wine Bottle", template_labels=["empty_wine_bottle"]),
        CatalogItem(id="exodus_modules", name="Exodus Modules", template_labels=["exodus_modules"]),
        # CatalogItem(id="expired_pasta", name="Expired Pasta", template_labels=["expired_pasta"]),
        # CatalogItem(id="expired_respirator", name="Expired Respirator", template_labels=["expired_respirator"]),
        # CatalogItem(id="explosive_compound", name="Explosive Compound", template_labels=["explosive_compound"]),
        CatalogItem(id="fabric", name="Fabric", template_labels=["fabric"]),
        # CatalogItem(id="faded_photograph", name="Faded Photograph", template_labels=["faded_photograph"]),
        # CatalogItem(id="fertilizer", name="Fertilizer", template_labels=["fertilizer"]),
        # CatalogItem(id="film_reel", name="Film Reel", template_labels=["film_reel"]),
        # CatalogItem(id="fine_wristwatch", name="Fine Wristwatch", template_labels=["fine_wristwatch"]),
        # CatalogItem(id="fireball_burner", name="Fireball Burner", template_labels=["fireball_burner"]),
        CatalogItem(id="flow_controller", name="Flow Controller", template_labels=["flow_controller"]),
        # CatalogItem(id="fossilized_lightning", name="Fossilized Lightning", template_labels=["fossilized_lightning"]),
        CatalogItem(id="frequency_modulation_box", name="Frequency Modulation Box", template_labels=["frequency_modulation_box"]),
        CatalogItem(id="fried_motherboard", name="Fried Motherboard", template_labels=["fried_motherboard"]),
        # CatalogItem(id="frying_pan", name="Frying Pan", template_labels=["frying_pan"]),
        CatalogItem(id="garlic_press", name="Garlic Press", template_labels=["garlic_press"]),
        CatalogItem(id="geiger_counter", name="Geiger Counter", template_labels=["geiger_counter"]),
        # CatalogItem(id="great_mullein", name="Great Mullein", template_labels=["great_mullein"]),
        CatalogItem(id="headphones", name="Headphones", template_labels=["headphones"]),
        CatalogItem(id="heavy_gun_parts", name="Heavy Gun Parts", template_labels=["heavy_gun_parts"]),
        CatalogItem(id="hornet_driver", name="Hornet Driver", template_labels=["hornet_driver"]),
        # CatalogItem(id="household_cleaner", name="Household Cleaner", template_labels=["household_cleaner"]),
        CatalogItem(id="humidifier", name="Humidifier", template_labels=["humidifier"]),
        # CatalogItem(id="ice_cream_scooper", name="Ice Cream Scooper", template_labels=["ice_cream_scooper"]),
        # CatalogItem(id="impure_arc_coolant", name="Impure ARC Coolant", template_labels=["impure_arc_coolant"]),
        CatalogItem(id="industrial_battery", name="Industrial Battery", template_labels=["industrial_battery"]),
        CatalogItem(id="industrial_charger", name="Industrial Charger", template_labels=["industrial_charger"]),
        CatalogItem(id="industrial_magnet", name="Industrial Magnet", template_labels=["industrial_magnet"]),
        CatalogItem(id="ion_sputter", name="Ion Sputter", template_labels=["ion_sputter"]),
        CatalogItem(id="laboratory_reagents", name="Laboratory Reagents", template_labels=["laboratory_reagents"]),
        # CatalogItem(id="lances_mixtape", name="Lances Mixtape", template_labels=["lances_mixtape"]),
        CatalogItem(id="leaper_pulse_unit", name="Leaper Pulse Unit", template_labels=["leaper_pulse_unit"]),
        CatalogItem(id="lemon", name="Lemon", template_labels=["lemon"]),
        CatalogItem(id="light_bulb", name="Light Bulb", template_labels=["light_bulb"]),
        CatalogItem(id="light_gun_parts", name="Light Gun Parts", template_labels=["light_gun_parts"]),
        CatalogItem(id="magnet", name="Magnet", template_labels=["magnet"]),
        CatalogItem(id="magnetic_accelerator", name="Magnetic Accelerator", template_labels=["magnetic_accelerator"]),
        CatalogItem(id="magnetron", name="Magnetron", template_labels=["magnetron"]),
        # CatalogItem(id="matriarch_reactor", name="Matriarch Reactor", template_labels=["matriarch_reactor"]),
        CatalogItem(id="mechanical_components", name="Mechanical Components", template_labels=["mechanical_components"]),
        CatalogItem(id="medium_gun_parts", name="Medium Gun Parts", template_labels=["medium_gun_parts"]),
        CatalogItem(id="metal_brackets", name="Metal Brackets", template_labels=["metal_brackets"]),
        CatalogItem(id="metal_parts", name="Metal Parts", template_labels=["metal_parts"]),
        # CatalogItem(id="microscope", name="Microscope", template_labels=["microscope"]),
        CatalogItem(id="mini_centrifuge", name="Mini Centrifuge", template_labels=["mini_centrifuge"]),
        # CatalogItem(id="mod_components", name="Mod Components", template_labels=["mod_components"]),
        # CatalogItem(id="moss", name="Moss", template_labels=["moss"]),
        CatalogItem(id="motor", name="Motor", template_labels=["motor"]),
        # CatalogItem(id="mushroom", name="Mushroom", template_labels=["mushroom"]),
        # CatalogItem(id="music_album", name="Music Album", template_labels=["music_album"]),
        # CatalogItem(id="music_box", name="Music Box", template_labels=["music_box"]),
        # CatalogItem(id="number_plate", name="Number Plate", template_labels=["number_plate"]),
        # CatalogItem(id="oil", name="Oil", template_labels=["oil"]),
        CatalogItem(id="olives", name="Olives", template_labels=["olives"]),
        # CatalogItem(id="painted_box", name="Painted Box", template_labels=["painted_box"]),
        CatalogItem(id="plastic_parts", name="Plastic Parts", template_labels=["plastic_parts"]),
        # CatalogItem(id="playing_cards", name="Playing Cards", template_labels=["playing_cards"]),
        # CatalogItem(id="polluted_air_filter", name="Polluted Air Filter", template_labels=["polluted_air_filter"]),
        # CatalogItem(id="pop_trigger", name="Pop Trigger", template_labels=["pop_trigger"]),
        # CatalogItem(id="portable_tv", name="Portable TV", template_labels=["portable_tv"]),
        # CatalogItem(id="poster_of_natural_wonders", name="Poster Of Natural Wonders", template_labels=["poster_of_natural_wonders"]),
        # CatalogItem(id="pottery", name="Pottery", template_labels=["pottery"]),
        # CatalogItem(id="power_rod", name="Power Rod", template_labels=["power_rod"]),
        # CatalogItem(id="power_bank", name="Power Bank", template_labels=["power_bank"]),
        CatalogItem(id="power_cable", name="Power Cable", template_labels=["power_cable"]),
        CatalogItem(id="prickly_pear", name="Prickly Pear", template_labels=["prickly_pear"]),
        CatalogItem(id="processor", name="Processor", template_labels=["processor"]),
        CatalogItem(id="projector", name="Projector", template_labels=["projector"]),
        # CatalogItem(id="queen_reactor", name="Queen Reactor", template_labels=["queen_reactor"]),
        # CatalogItem(id="radio", name="Radio", template_labels=["radio"]),
        # CatalogItem(id="radio_relay", name="Radio Relay", template_labels=["radio_relay"]),
        # CatalogItem(id="recorder", name="Recorder", template_labels=["recorder"]),
        # CatalogItem(id="red_coral_jewelry", name="Red Coral Jewelry", template_labels=["red_coral_jewelry"]),
        # CatalogItem(id="remote_control", name="Remote Control", template_labels=["remote_control"]),
        # CatalogItem(id="resin", name="Resin", template_labels=["resin"]),
        # CatalogItem(id="ripped_safety_vest", name="Ripped Safety Vest", template_labels=["ripped_safety_vest"]),
        CatalogItem(id="rocketeet_driver", name="Rocketeet Driver", template_labels=["rocketeet_driver"]),
        # CatalogItem(id="rocket_thruster", name="Rocket Thruster", template_labels=["rocket_thruster"]),
        # CatalogItem(id="roots", name="Roots", template_labels=["roots"]),
        CatalogItem(id="rope", name="Rope", template_labels=["rope"]),
        # CatalogItem(id="rosary", name="Rosary", template_labels=["rosary"]),
        # CatalogItem(id="rotary_encoder", name="Rotary Encoder", template_labels=["rotary_encoder"]),
        # CatalogItem(id="rubber_duck", name="Rubber Duck", template_labels=["rubber_duck"]),
        # CatalogItem(id="rubber_pad", name="Rubber Pad", template_labels=["rubber_pad"]),
        CatalogItem(id="rubber_parts", name="Rubber Parts", template_labels=["rubber_parts"]),
        # CatalogItem(id="ruined_accordon", name="Ruined Accordon", template_labels=["ruined_accordon"]),
        # CatalogItem(id="ruined_baton", name="Ruined Baton", template_labels=["ruined_baton"]),
        # CatalogItem(id="ruined_handcuffs", name="Ruined Handcuffs", template_labels=["ruined_handcuffs"]),
        # CatalogItem(id="ruined_parachute", name="Ruined Parachute", template_labels=["ruined_parachute"]),
        # CatalogItem(id="ruined_riot_shield", name="Ruined Riot Shield", template_labels=["ruined_riot_shield"]),
        CatalogItem(id="ruined_tactical_vest", name="Ruined Tactical Vest", template_labels=["ruined_tactical_vest"]),
        CatalogItem(id="rusted_bolts", name="Rusted Bolts", template_labels=["rusted_bolts"]),
        CatalogItem(id="rusted_gear", name="Rusted Gear", template_labels=["rusted_gear"]),
        CatalogItem(id="rusted_shut_medical_kit", name="Rusted Shut Medical Kit", template_labels=["rusted_shut_medical_kit"]),
        CatalogItem(id="rusted_tools", name="Rusted Tools", template_labels=["rusted_tools"]),
        # CatalogItem(id="rusty_arc_steel", name="Rusty ARC Steel", template_labels=["rusty_arc_steel"]),
        # CatalogItem(id="sample_cleaner", name="Sample Cleaner", template_labels=["sample_cleaner"]),
        CatalogItem(id="sensors", name="Sensors", template_labels=["sensors"]),
        # CatalogItem(id="sentinel_firing_core", name="Sentinel Firing Core", template_labels=["sentinel_firing_core"]),
        CatalogItem(id="shredder_gryo", name="Shredder Gryo", template_labels=["shredder_gryо"]),
        CatalogItem(id="signal_amplifier", name="Signal Amplifier", template_labels=["signal_amplifier"]),
        # CatalogItem(id="silver_teaspoon_set", name="Silver Teaspoon Set", template_labels=["silver_teaspoon_set"]),
        CatalogItem(id="simple_gun_parts", name="Simple Gun Parts", template_labels=["simple_gun_parts"]),
        CatalogItem(id="snap_blast_grenades", name="Snap Blast Grenades", template_labels=["snap_blast_grenades"]),
        # CatalogItem(id="snitch_scanner_png", name="Snitch Scanner", template_labels=["snitch_scanner_png"]),
        CatalogItem(id="speaker_component", name="Speaker Component", template_labels=["speaker_component"]),
        CatalogItem(id="spectrometer", name="Spectrometer", template_labels=["spectrometer"]),
        CatalogItem(id="spectrum_analyizer", name="Spectrum Analyizer", template_labels=["spectrum_analyizer"]),
        CatalogItem(id="spotter_relay", name="Spotter Relay", template_labels=["spotter_relay"]),
        CatalogItem(id="spring_cushion_png", name="Spring Cushion", template_labels=["spring_cushion_png"]),
        # CatalogItem(id="statuette", name="Statuette", template_labels=["statuette"]),
        CatalogItem(id="steel_spring", name="Steel Spring", template_labels=["steel_spring"]),
        # CatalogItem(id="surveyor_vault", name="Surveyor Vault", template_labels=["surveyor_vault"]),
        CatalogItem(id="synthesized_fuel", name="Synthesized Fuel", template_labels=["synthesized_fuel"]),
        CatalogItem(id="syringe", name="Syringe", template_labels=["syringe"]),
        # CatalogItem(id="tattered_arc_lining", name="Tattered ARC Lining", template_labels=["tattered_arc_lining"]),
        CatalogItem(id="tattered_clothes", name="Tattered Clothes", template_labels=["tattered_clothes"]),
        # CatalogItem(id="telemetry_transceiver", name="Telemetry Transceiver", template_labels=["telemetry_transceiver"]),
        # CatalogItem(id="thermostat", name="Thermostat", template_labels=["thermostat"]),
        CatalogItem(id="tick_pod", name="Tick Pod", template_labels=["tick_pod"]),
        CatalogItem(id="toaster", name="Toaster", template_labels=["toaster"]),
        CatalogItem(id="torn_blanket", name="Torn Blanket", template_labels=["torn_blanket"]),
        # CatalogItem(id="torn_book", name="Torn Book", template_labels=["torn_book"]),
        # CatalogItem(id="turbo_pump", name="Turbo Pump", template_labels=["turbo_pump"]),
        # CatalogItem(id="unusable_weapon", name="Unusable Weapon", template_labels=["unusable_weapon"]),
        # CatalogItem(id="vase", name="Vase", template_labels=["vase"]),
        # CatalogItem(id="very_comfortable_pillow", name="Very Comfortable Pillow", template_labels=["very_comfortable_pillow"]),
        # CatalogItem(id="volcanic_rock", name="Volcanic Rock", template_labels=["volcanic_rock"]),
        CatalogItem(id="voltage_converter", name="Voltage Converter", template_labels=["voltage_converter"]),
        CatalogItem(id="wasp_driver", name="Wasp Driver", template_labels=["wasp_driver"]),
        # CatalogItem(id="water_filter", name="Water Filter", template_labels=["water_filter"]),
        CatalogItem(id="water_pump", name="Water Pump", template_labels=["water_pump"]),
        CatalogItem(id="wires", name="Wires", template_labels=["wires"]),
    ]
    return {i.id: i for i in items}
